service name:udevd notify:none env:-/etc/default/udevd pid:udevd log [S12345789] udevd $UDEVD_ARGS -- Device event daemon (udev)

run nowarn if:udevd cgroup.init,name:udevadm :1 [S] <service/udevd/ready> log udevadm trigger --action=add   -- Requesting device events
run nowarn if:udevd cgroup.init,name:udevadm :2 [S] <service/udevd/ready> log udevadm settle &               -- Waiting for udev to finish
